name: Build Docker image

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use example env file
      run: cp .env.example .env

    - name: Build Docker image
      run: docker build .
